/*
 * oKaPIBackend API
 *
 * oKaPIBackend API documentation
 *
 * API version: 6.3.1
 * Contact: software@sma.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ProductReleaseDto struct {
	Id string `json:"id,omitempty"`
	CreateTime time.Time `json:"createTime,omitempty"`
	CreateUser string `json:"createUser,omitempty"`
	LastModifiedTime time.Time `json:"lastModifiedTime,omitempty"`
	LastModifiedUser string `json:"lastModifiedUser,omitempty"`
	Properties map[string]string `json:"properties,omitempty"`
	Revision string `json:"revision,omitempty"`
	RevisionPrefix string `json:"revisionPrefix,omitempty"`
	RevisionMajor string `json:"revisionMajor,omitempty"`
	RevisionMinor string `json:"revisionMinor,omitempty"`
	RevisionPatch string `json:"revisionPatch,omitempty"`
	RevisionQualifier string `json:"revisionQualifier,omitempty"`
	RevisionCalculated string `json:"revisionCalculated,omitempty"`
	Kpi map[string]string `json:"kpi,omitempty"`
	BadgeURL string `json:"badgeURL,omitempty"`
	Rating string `json:"rating,omitempty"`
	Description string `json:"description,omitempty"`
	DownloadUrl string `json:"downloadUrl,omitempty"`
	Product *ProductDto `json:"product,omitempty"`
	ReleaseManagerStatus string `json:"releaseManagerStatus,omitempty"`
	PwnedNotes map[string]string `json:"pwnedNotes,omitempty"`
}
