/*
 * oKaPIBackend API
 *
 * oKaPIBackend API documentation
 *
 * API version: 6.3.1
 * Contact: software@sma.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SonarBranchDto struct {
	Branch string `json:"branch,omitempty"`
	Status string `json:"status,omitempty"`
	Ts int32 `json:"ts,omitempty"`
	TsOrig string `json:"tsOrig,omitempty"`
	Metrics *SonarMetricsDto `json:"metrics,omitempty"`
	Badge string `json:"badge,omitempty"`
	Version string `json:"version,omitempty"`
	Revision string `json:"revision,omitempty"`
}
