/*
 * oKaPIBackend API
 *
 * oKaPIBackend API documentation
 *
 * API version: 6.3.1
 * Contact: software@sma.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AddressStandardClaim struct {
	Region string `json:"region,omitempty"`
	Country string `json:"country,omitempty"`
	StreetAddress string `json:"streetAddress,omitempty"`
	PostalCode string `json:"postalCode,omitempty"`
	Formatted string `json:"formatted,omitempty"`
	Locality string `json:"locality,omitempty"`
}
