/*
 * oKaPIBackend API
 *
 * oKaPIBackend API documentation
 *
 * API version: 6.3.1
 * Contact: software@sma.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SonarProjectDto struct {
	Name string `json:"name,omitempty"`
	Ts int32 `json:"ts,omitempty"`
	Branches []SonarBranchDto `json:"branches,omitempty"`
}
