/*
 * oKaPIBackend API
 *
 * oKaPIBackend API documentation
 *
 * API version: 6.3.1
 * Contact: software@sma.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ModuleVersionImportDto struct {
	ModuleName string `json:"moduleName,omitempty"`
	Version string `json:"version,omitempty"`
	Description string `json:"description,omitempty"`
	ModuleTags []string `json:"moduleTags,omitempty"`
	Metrics map[string]string `json:"metrics"`
}
