/*
 * oKaPIBackend API
 *
 * oKaPIBackend API documentation
 *
 * API version: 6.3.1
 * Contact: software@sma.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SonarMetricsDto struct {
	Bugs *SonarRatingDto `json:"bugs,omitempty"`
	Sqale *SonarRatingDto `json:"sqale,omitempty"`
	DuplicatedLinesDensity *SonarRatingDto `json:"duplicated_lines_density,omitempty"`
	Vulnerabilities *SonarRatingDto `json:"vulnerabilities,omitempty"`
	Coverage *SonarRatingDto `json:"coverage,omitempty"`
	CodeSmells *SonarRatingDto `json:"code_smells,omitempty"`
	Ncloc *SonarRatingDto `json:"ncloc,omitempty"`
}
