/*
 * oKaPIBackend API
 *
 * oKaPIBackend API documentation
 *
 * API version: 6.3.1
 * Contact: software@sma.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type OidcIdToken struct {
	TokenValue string `json:"tokenValue,omitempty"`
	IssuedAt time.Time `json:"issuedAt,omitempty"`
	ExpiresAt time.Time `json:"expiresAt,omitempty"`
	Claims map[string]interface{} `json:"claims,omitempty"`
	Audience []string `json:"audience,omitempty"`
	Subject string `json:"subject,omitempty"`
	AuthorizedParty string `json:"authorizedParty,omitempty"`
	AccessTokenHash string `json:"accessTokenHash,omitempty"`
	AuthenticationContextClass string `json:"authenticationContextClass,omitempty"`
	AuthenticationMethods []string `json:"authenticationMethods,omitempty"`
	AuthorizationCodeHash string `json:"authorizationCodeHash,omitempty"`
	Issuer string `json:"issuer,omitempty"`
	AuthenticatedAt time.Time `json:"authenticatedAt,omitempty"`
	Nonce string `json:"nonce,omitempty"`
	Address *AddressStandardClaim `json:"address,omitempty"`
	Locale string `json:"locale,omitempty"`
	FullName string `json:"fullName,omitempty"`
	ZoneInfo string `json:"zoneInfo,omitempty"`
	Email string `json:"email,omitempty"`
	PreferredUsername string `json:"preferredUsername,omitempty"`
	PhoneNumberVerified bool `json:"phoneNumberVerified,omitempty"`
	GivenName string `json:"givenName,omitempty"`
	FamilyName string `json:"familyName,omitempty"`
	MiddleName string `json:"middleName,omitempty"`
	NickName string `json:"nickName,omitempty"`
	Picture string `json:"picture,omitempty"`
	Website string `json:"website,omitempty"`
	EmailVerified bool `json:"emailVerified,omitempty"`
	Gender string `json:"gender,omitempty"`
	Birthdate string `json:"birthdate,omitempty"`
	PhoneNumber string `json:"phoneNumber,omitempty"`
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	Profile string `json:"profile,omitempty"`
}
