/*
 * oKaPIBackend API
 *
 * oKaPIBackend API documentation
 *
 * API version: 6.3.1
 * Contact: software@sma.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SonarRatingDto struct {
	Rating string `json:"rating,omitempty"`
	Value float64 `json:"value,omitempty"`
}
