/*
 * oKaPIBackend API
 *
 * oKaPIBackend API documentation
 *
 * API version: 6.3.1
 * Contact: software@sma.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type ProductReleaseImportDto struct {
	ProductName string `json:"productName,omitempty"`
	ProductLongName string `json:"productLongName,omitempty"`
	SusyId int32 `json:"susyId,omitempty"`
	Version string `json:"version,omitempty"`
	Description string `json:"description,omitempty"`
	ProductTags []string `json:"productTags,omitempty"`
	DownloadUrl string `json:"downloadUrl,omitempty"`
	ReleaseCreateTime time.Time `json:"releaseCreateTime,omitempty"`
	ReleaseCreateUser string `json:"releaseCreateUser,omitempty"`
	ModuleVersionImportDtoSet []ModuleVersionImportDto `json:"moduleVersionImportDtoSet,omitempty"`
}
