/*
 * oKaPIBackend API
 *
 * oKaPIBackend API documentation
 *
 * API version: 6.3.1
 * Contact: software@sma.de
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PingDto struct {
	Pong bool `json:"pong,omitempty"`
	ScheduleTs float64 `json:"schedule_ts,omitempty"`
}
